title: Malcolm Detering # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aspiring data analyst/data engineer looking to begin my career. I am a recent graduate of the University of Washington, where I recieved a Bachelors of Science in Atmospheric Sciences with a focus on Data Science. I am profficient in multiple data related tools such as Python, R, SQL, Tableau, Power BI, Excel and more. I am a fiecely loyal, hardworking, team player that would make a great addition to a data analytics or data engineering team.
  <br><br>
  This portfolio is meant to showcase some of my personal projects that prove my expertise in multiple areas of data analytics and data engineering. These projects were focused around different areas of each subject and each make use of varying tools essential for wokring as a data analyst.  
  <br><br>
  <a href="https://www.linkedin.com/in/malcolm-detering/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
